name: pytest-env

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pytest:
    name: ${{ matrix.name }}
    runs-on: "${{ matrix.os }}"

    env:
      PYTHON_VERSION: "${{ matrix.python-version }}"
      TESTS: "tests/"

    strategy:
      # Prevent all build to stop if a single one fails
      fail-fast: false

      matrix:
        name: [
           python38-ubuntu2004,
           python38-ubuntu2204,
           python39-ubuntu2004,
           python39-ubuntu2204
        ]
        include:
        - name: python38-ubuntu2004
          python-version: 3.8
          os: ubuntu-20.04

        - name: python38-ubuntu2204
          python-version: 3.8
          os: ubuntu-22.04

        - name: python39-ubuntu2004
          python-version: 3.9
          os: ubuntu-20.04

        - name: python39-ubuntu2204
          python-version: 3.9
          os: ubuntu-22.04

    steps:
    - name: Checkout simple_functions
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest tests/